name: Java CI

on:
  push:
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Run Checkstyle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: checkstyleMain --stacktrace
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
      - name: Build API
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      
